version: '4.14'

services: 
    mysqldb:
        image: mysql:latest
        ports:
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=pinterest_db
        volumes: 
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
        hostname: mysql
    
    pinterest_flask:
        build:
            context: .
        ports:
        - 5000:5000
        depends_on: 
            - pinterest_db
volumes: 
    mysqlVolume:
    mysqlConfig: